/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_NativeConverter */

#ifndef _Included_pkg_NativeConverter
#define _Included_pkg_NativeConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pkg_NativeConverter
 * Method:    convert
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_pkg_NativeConverter_convert
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
